import { spawnSync } from 'node:child_process';
import { createRequire } from 'node:module';
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
const require = createRequire(import.meta.url);
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const numbro = require('numbro');
if (require('bignumber.js/package.json').version !== '9.3.1') throw new Error('Expected bignumber.js 9.3.1 from the lockfile');
if (numbro.version !== '2.5.0') throw new Error('Expected numbro 2.5.0');
for (const f of readdirSync(resolve(root, 'tools/node_modules/numbro/languages')).sort()) numbro.registerLanguage(require(`numbro/languages/${f}`));
const locales = Object.values(numbro.languages()).sort((a,b)=>a.languageTag<b.languageTag?-1:a.languageTag>b.languageTag?1:0);
const quote = s => JSON.stringify(s);
const snake = s => s.replace(/[A-Z]/g, c=>'_'+c.toLowerCase());
const enums = new Set(['output','base','currencyPosition','negative','forceAverage']);
function options(o={}) { return '.{ '+Object.entries(o).map(([k,v])=>`.${snake(k)} = ${enums.has(k)?'.'+v: typeof v==='string'?quote(v):typeof v==='object'?abbrevs(v):v}`).join(', ')+' }'; }
function abbrevs(o) { return '.{ '+Object.entries(o).map(([k,v])=>`.${k} = ${quote(v)}`).join(', ')+' }'; }
let z = '// Generated by tools/generate.mjs from numbro 2.5.0. See NOTICE.\nconst t = @import("types.zig");\nconst std = @import("std");\npub const all = [_]t.Locale{\n';
for (const l of locales) {
  const f=l.ordinal.toString();
  const rule = l.languageTag==='tr-TR'?'turkish':f.includes('remainder')?'dutch':f.includes('ème')?'french':f.includes('"er"')?'spanish':f.includes('"st"')?'english':'constant';
  z+=`.{ .tag = ${quote(l.languageTag)}, .thousands = ${quote(l.delimiters.thousands)}, .decimal = ${quote(l.delimiters.decimal)}, .thousands_size = ${l.delimiters.thousandsSize||3}, .abbreviations = ${abbrevs(l.abbreviations)}, .currency_symbol = ${quote(l.currency.symbol)}, .currency_code = ${quote(l.currency.code)}, .currency_position = .${l.currency.position||'postfix'}, .ordinal_rule = .${rule}, .ordinal_constant = ${quote(rule==='constant'?l.ordinal(1):'')},\n`;
  for(const [key,dest] of [['defaults','defaults'],['currencyFormat','currency_format'],['ordinalFormat','ordinal_format'],['byteFormat','byte_format'],['percentageFormat','percentage_format'],['timeDefaults','time_format']]) if(l[key]) z+=`.${dest} = ${options(l[key])},\n`;
  if(l.bytes) for(const [k,d] of [['binarySuffixes','binary_suffixes'],['decimalSuffixes','decimal_suffixes']]) if(l.bytes[k]) z+=`.${d} = .{ ${l.bytes[k].map(quote).join(', ')} },\n`;
  z+=`.formats = &.{ ${Object.entries(l.formats||{}).map(([name,o])=>`.{ .name = ${quote(name)}, .options = ${options(o)} }`).join(', ')} } },\n`;
}
z+='};\n/// Find an exact locale tag or return UnknownLocale; result has static lifetime.\npub fn get(tag: []const u8) t.Error!*const t.Locale { for (&all) |*l| if (std.mem.eql(u8, tag, l.tag)) return l; return error.UnknownLocale; }\n/// Find a locale, using only the explicitly requested fallback tag.\npub fn getOr(tag: []const u8, fallback: []const u8) t.Error!*const t.Locale { return get(tag) catch get(fallback); }\n';
writeFileSync(resolve(root,'src/locales.zig'),z);
const patterns=['0,0.0000','0,0','+0,0','0,0.0','0.000','0[.]00000','(0,0.0000)','.00','(.00)','0.00000','0.0[0000]','0.0a','0 a','0a','0a.00','0o','1a','2a','3a','10a','$0,0.00','0,0[.]00 $','$ 0,0[.]00','($0,0)','$0.00','($ 0.00 a)','0b','0 b','0.0b','0.000 b','0d','0bd','0%','0.000%','0 %','(0.000 %)','00:00:00','0K','0M','0B','0T','{USD }0,0.00{ net}'];
const values=[0,1,2,3,11,12,13,21,52,100,-1,-10000,-0.23,0.23,10000.23,10000.1234,1230974,1460,-104000,233434,233000,1234567891,2048,7884486213,3467479682787,0.974878234,-0.43,25,238,63846];
const objects=[{}, {thousandSeparated:true,mantissa:2},{trimMantissa:true,mantissa:4},{optionalMantissa:true,mantissa:2},{average:true},{average:true,mantissa:2},{average:true,totalLength:4,spaceSeparated:true},{output:'currency'},{output:'percent'},{output:'byte',base:'binary'},{output:'time'},{output:'ordinal'},{exponential:true},{exponential:true,characteristic:3,mantissa:2},{prefixSymbol:true,output:'percent',spaceSeparated:true},{currencyPosition:'infix',output:'currency',mantissa:2},{forceSign:true,negative:'parenthesis',mantissa:2}];
const fixtures=[];
for(const l of locales) {
 numbro.setLanguage(l.languageTag);
 for(const v of values) for(const p of patterns) fixtures.push({locale:l.languageTag,value:v,pattern:p,expected:numbro(v).format(p)});
 for(const v of values) for(const o of objects) fixtures.push({locale:l.languageTag,value:v,options:o,expected:numbro(v).format(o)});
 for(const [name,o] of Object.entries(l.formats||{})) for(const v of [0,1000.234,-1234567]) fixtures.push({locale:l.languageTag,value:v,named:name,expected:numbro(v).format(o)});
}
const ordinals=[];
for(const l of locales) for(const value of [0,1,2,3,8,9,10,11,12,13,20,21,100,101,111,200,1000,-1,-11,1.5]) ordinals.push({locale:l.languageTag,value,expected:l.ordinal(value)||''});
const reads=[];
for(const l of locales) { numbro.setLanguage(l.languageTag); for(const v of [0,1,-1,1000.25,1234567,-0.43,63846]) for(const p of ['0,0.00','$0,0.00','0.00a','0%','0 b','0o','00:00:00']) {const text=numbro(v).format(p);const expected=numbro.unformat(text);if(Number.isFinite(expected))reads.push({locale:l.languageTag,text,expected});} }
const edgeValues=[-0,0.5,-0.5,1.005,-1.005,2.675,-2.675,999.5,999499,999500,0.000001,-0.000001,1e-7,-1e-7,1e-20,-1e-20,1e20,-1e20,1e21,-1e21,Number.MAX_VALUE,Number.MIN_VALUE,9007199254740991,1.2345678901234567];
const edgeOptions=[...objects,{mantissa:38},{characteristic:6,mantissa:3},{output:'currency',mantissa:2,currencySymbol:'USD',spaceSeparatedCurrency:true,negative:'parenthesis'},{average:true,lowPrecision:false},{forceAverage:'million',mantissa:3},{mantissa:2,rounding:'floor'},{mantissa:2,rounding:'ceil'},{mantissa:2,rounding:'trunc'},{mantissa:2,rounding:'half_away'},{mantissa:2,rounding:'half_even'},{output:'byte',base:'general',mantissa:3},{output:'byte',base:'decimal',mantissa:3},{prefix:'about ',postfix:' net',mantissa:2}];
const rounding={floor:Math.floor,ceil:Math.ceil,trunc:Math.trunc,half_away:x=>Math.sign(x)*Math.round(Math.abs(x)),half_even:x=>{const f=Math.floor(x),r=x-f;return r>0.5||r===0.5&&f%2!==0?f+1:f;}};
for(const tag of ['en-US','es-CL','fr-FR','de-CH','ja-JP','tr-TR']) {
 numbro.setLanguage(tag);
 for(const value of edgeValues) for(const o of edgeOptions) {
  const ref={...o}; if(ref.rounding){ref.roundingFunction=rounding[ref.rounding];delete ref.rounding;}
  const expected=numbro(value).format(ref);
  fixtures.push({locale:tag,value,options:o,expected});
 }
 for(const zero of ['N/A','zero']) { numbro.zeroFormat(zero); for(const o of [{}, {output:'currency',mantissa:2}, {output:'percent',mantissa:2}, {average:true}]) fixtures.push({locale:tag,value:0,options:o,zero_format:zero,expected:numbro(0).format(o)}); }
 numbro.zeroFormat(null);
}
let seed=0x5a17c0de;
function random(){seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/2**32;}
for(let i=0;i<512;i++) {
 const tag=['en-US','es-CL','fr-FR'][i%3]; numbro.setLanguage(tag);
 const value=(random()*2-1)*10**Math.floor(random()*24-12);
 for(const p of ['0,0.00','0.000','0[.]00','(0,0)','0.00a','$0,0.00','0.0b','0.00%']) fixtures.push({locale:tag,value,pattern:p,expected:numbro(value).format(p)});
 const o={exponential:true,mantissa:5};fixtures.push({locale:tag,value,options:o,expected:numbro(value).format(o)});
}
const operations=[];
for(const a of [0,0.1,-0.1,1,1.005,1e-20,1e20,1234567.89,-999.99]) for(const b of [0,0.2,-0.2,3,1e-20,1e20]) for(const op of ['add','subtract','multiply','divide','difference']) { const number=numbro(a); const result=number[op](b); const expected=op==='difference'?result:number.value(); if(Number.isFinite(expected)) operations.push({a,b,op,expected}); }
writeFileSync(resolve(root,'src/fixtures.json'),JSON.stringify({reference:'numbro@2.5.0',fixtures,ordinals,reads,operations}));
const formatted=spawnSync('zig',['fmt','src/locales.zig'],{cwd:root,stdio:'pipe'});if(formatted.status!==0)throw new Error(formatted.stderr.toString());
console.log(`${locales.length} locales, ${fixtures.length} formats, ${ordinals.length} ordinals, ${reads.length} reads, ${operations.length} operations`);
